[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "cohfit"
dynamic = ["version"]
description = 'A non-parametrized frequentist construction of confidence intervals for phenomenological models in the COHERENT Collaboration '
readme = "README.md"
requires-python = ">=3.9"
license = "MIT"
keywords = []
authors = [
  { name = "Charlie Prior", email = "charlie@charlieprior.com" },
  { name = "Ryan Bouabid", email="ryan-bouabid@live.com" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
  "awkward",
  "awkward_cpp",
  "contourpy",
  "cramjam",
  "cycler",
  "fonttools",
  "fsspec",
  "iminuit",
  "kiwisolver",
  "llvmlite",
  "matplotlib",
  "numba",
  "numpy",
  "packaging",
  "pillow",
  "pyparsing",
  "python-dateutil",
  "SciencePlots",
  "scipy",
  "six",
  "threadpoolctl",
  "tqdm",
  "uproot",
  "xxhash",
  "pyjson5"
]

[project.urls]
Documentation = "https://github.com/BarbeauGroup/cohfit#readme"
Issues = "https://github.com/BarbeauGroup/cohfit/issues"
Source = "https://github.com/BarbeauGroup/cohfit"

[tool.hatch.version]
path = "src/cohfit/__about__.py"

[tool.hatch.envs.types]
extra-dependencies = [
  "mypy>=1.0.0",
]
[tool.hatch.envs.types.scripts]
check = "mypy --install-types --non-interactive {args:src/cohfit tests}"

[tool.coverage.run]
source_pkgs = ["cohfit", "tests"]
branch = true
parallel = true
omit = [
  "src/cohfit/__about__.py",
]

[tool.coverage.paths]
cohfit = ["src/cohfit", "*/cohfit/src/cohfit"]
tests = ["tests", "*/cohfit/tests"]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]
