name = "pb_glass_20m"

[detector]
distance = 20.0
_distance_units = "m"
mass = 10200.0
_mass_units = "kg"
molar_mass = 207.98
_molar_mass_units = "g/mol"
detector_matrix = "data/flux_transfer_matrices/pb_CC_dtm.npy"
detector_matrix_dx = 1.0
flux_matrix_dx = 1.0
asimov_data_file = "data/pb_asimov.txt"
observable_flavors = ["nuE"]

[[detector.isotopes]]
name = "Pb208"
mass = 207.98
abundance = 1.0
flux_matrix = "data/flux_transfer_matrices/pb_CC_normed_trunc.npy"

[detector.systematics]
flux = 0.1

[detector.norms]
ssb = 0.0
brn = 0.0
nin = 0.0

[beam]
pot = 1.58e+23

[analysis]
unbinned = false
energy_roi = [0.0, 60.0]
time_roi = [0.0, 15.0]
energy_bins = [0.0, 10.0, 20.0, 30.0, 40.0, 50.0, 60.0]
_energy_units = "MeV"
time_bins = [0.0, 0.125, 0.25, 0.375, 0.5, 0.625, 0.75, 0.875, 1.0, 2.0, 4.0, 6.0, 15.0]
_time_units = "us"